### ISSUE TITLE
To investigate -- changing the IrodsEntity(acl=(),..) broke lots of unit tests

### ISSUE THREAD

**Issue by irinaColgiu** [wtsi-hgi/python-baton-wrapper#28]
It seems that changing the default value of the constructor parameter access_control_list in IrodsEntity and in DataObject to an empty tuple ()  (commit bec49ad7cc1c086234b335161a281d51ccf3a6c2) broke quite a few unittests. To investigate and fix the tests accordingly.

**Comment by Xophmeister** [comment]
This seems to be because a tuple can't be serialised into JSON:

```
Traceback (most recent call last):
  File "/Users/ch12/Projects/forks/python-baton-wrapper/baton/tests/test__baton_mappers.py", line 128, in test_get_by_path_when_entity_does_not_exist
    self.assertRaises(FileNotFoundError, self.create_mapper().get_by_path, "/invalid/name")
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/baton/_baton_mappers.py", line 64, in get_by_path
    path_json = self._path_to_baton_json(path)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/baton/_baton_mappers.py", line 161, in _path_to_baton_json
    return CollectionJSONEncoder().default(collection)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/json/builders.py", line 75, in default
    encoded = superclass.default(encoder, serializable)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/json/builders.py", line 75, in default
    encoded = superclass.default(encoder, serializable)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/json/_serialization.py", line 43, in default
    return serializer.serialize(serializable)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/serialization.py", line 36, in serialize
    encoded_value = self._serialize_property_value(value, mapping.serializer_cls)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/serialization.py", line 50, in _serialize_property_value
    return serializer.serialize(to_serialize)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/json/_converters.py", line 70, in serialize
    return self._encoder.default(serializable)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/json/builders.py", line 75, in default
    encoded = superclass.default(encoder, serializable)
  File "/Users/ch12/Projects/forks/python-baton-wrapper/venv/lib/python3.5/site-packages/hgijson/json/_serialization.py", line 41, in default
    return super().default(serializable)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: () is not JSON serializable
```

If you were to serialise a tuple into a JSON array, then deserialisation would be ambiguous (i.e., is it a list or is it a tuple?) One could use a list, in this instance, but code that uses tuples will still not work -- and there's good reason to use tuples instead of lists when, e.g., passing default parameters.

One could potentially live with the ambiguity (i.e., deserialise everything to lists), as they share the same iterable API, then its up to the code in question to either convert it to a list, or be careful with mutability.

**Comment by irinaColgiu** [comment]
On the other hand if the hgijson won't deal with tuples at all - as it is currently implemented - this means that you can only use this package to serialize data types that don't contain tuples...

**Comment by Xophmeister** [comment]
...It looks like Python's `json` does handle tuples just fine (and serialises them to JSON arrays, as discussed). It looks like hgijson also does the right thing, but I've yet to confirm. Hence the problem is therefore probably in the mapping definition for the JSON codec.

**Comment by Xophmeister** [comment]
...Yep, it looks like hgijson encodes an empty tuple correctly

**Comment by colin-nolan** [comment]
As Chris indicates, tests fail as they will start with a tuple, encode to an JSON array then decode back to a list which will not equate to the original tuple.

To decode back to tuples, you will need to write a decoder that would handle the conversion from List to Tuple (a TupleJSONDecoder could be added to primitive.py in hgijson that would do this.)

**Comment by colin-nolan** [comment]
Looks like commit https://github.com/wtsi-hgi/python-baton-wrapper/commit/bd5c0c93d1d67f58aa5a37dcb5e8401a76d7fa46 has got around this issue. Will close if unit tests pass.

**Comment by colin-nolan** [comment]
Unit tests failing ATM due to bug in https://github.com/wtsi-hgi/python-baton-wrapper/commit/4b9bca40f3bf2f9fd83051c4dc2aed7368107f6d. Fix commited in https://github.com/wtsi-hgi/python-baton-wrapper/commit/689f3a5c422f55a9af9b0393eb383483fc68523c - re-running tests.

**Comment by colin-nolan** [comment]
Tests now pass :).
